# Makefile: A standard Makefile for main.c


CFLAGS=-g -std=gnu99 -Wall -Wno-parentheses
#LDFLAGS=
LDLIBS= -lallegro -lallegro_primitives -lallegro_font -lallegro_ttf

all  : main
clean:
	/bin/rm -rf main main.o
# END OF FILE
